services:
  langflow:
    image: langflowai/langflow:latest
    ports:
      - "7860:7860"
    depends_on:
      - postgres
      - qdrant
    env_file: ".env"
    volumes:
      - langflow-data:/app/langflow
      - langflow-config:/app/config
    networks:
      - node-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: langflow
      POSTGRES_PASSWORD: langflow
      POSTGRES_DB: langflow
    ports:
      - "5432:5432"
    volumes:
      - langflow-postgres:/var/lib/postgresql/data
    networks:
      - node-network

  qdrant:
    image: qdrant/qdrant:latest
    hostname: qdrant
    ports:
      - "6333:6333"
    volumes:
      - langflow-qdrant:/qdrant/storage
    networks:
      - node-network

volumes:
  langflow-postgres:
  langflow-qdrant:
  langflow-data:
  langflow-config:


networks:
  node-network:
    driver: bridge